// Generated by gencpp from file active_contour/snake.msg
// DO NOT EDIT!


#ifndef ACTIVE_CONTOUR_MESSAGE_SNAKE_H
#define ACTIVE_CONTOUR_MESSAGE_SNAKE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace active_contour
{
template <class ContainerAllocator>
struct snake_
{
  typedef snake_<ContainerAllocator> Type;

  snake_()
    : x()
    , y()  {
    }
  snake_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)  {
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _x_type;
  _x_type x;

   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::active_contour::snake_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::active_contour::snake_<ContainerAllocator> const> ConstPtr;

}; // struct snake_

typedef ::active_contour::snake_<std::allocator<void> > snake;

typedef boost::shared_ptr< ::active_contour::snake > snakePtr;
typedef boost::shared_ptr< ::active_contour::snake const> snakeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::active_contour::snake_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::active_contour::snake_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace active_contour

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'active_contour': ['/home/osboxes/Desktop/CR_project/Cognitive-Robotics-Project/catkin_ws/src/active_contour/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::active_contour::snake_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::active_contour::snake_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::active_contour::snake_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::active_contour::snake_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::active_contour::snake_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::active_contour::snake_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::active_contour::snake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6a2e8d0a077dcd5656e4fe8efecc3b1";
  }

  static const char* value(const ::active_contour::snake_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6a2e8d0a077dcd5ULL;
  static const uint64_t static_value2 = 0x656e4fe8efecc3b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::active_contour::snake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "active_contour/snake";
  }

  static const char* value(const ::active_contour::snake_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::active_contour::snake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] x\n\
int64[] y\n\
";
  }

  static const char* value(const ::active_contour::snake_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::active_contour::snake_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct snake_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::active_contour::snake_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::active_contour::snake_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIVE_CONTOUR_MESSAGE_SNAKE_H
