// Generated by gencpp from file beginner_tut/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUT_MESSAGE_ADDTWOINTS_H
#define BEGINNER_TUT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <beginner_tut/AddTwoIntsRequest.h>
#include <beginner_tut/AddTwoIntsResponse.h>


namespace beginner_tut
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace beginner_tut


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tut::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tut::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner_tut::AddTwoInts > {
  static const char* value()
  {
    return "beginner_tut/AddTwoInts";
  }

  static const char* value(const ::beginner_tut::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tut::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::beginner_tut::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_tut::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tut::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tut::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tut::AddTwoIntsRequest> should match 
// service_traits::DataType< ::beginner_tut::AddTwoInts > 
template<>
struct DataType< ::beginner_tut::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tut::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tut::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tut::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::beginner_tut::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_tut::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tut::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tut::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tut::AddTwoIntsResponse> should match 
// service_traits::DataType< ::beginner_tut::AddTwoInts > 
template<>
struct DataType< ::beginner_tut::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tut::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tut::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUT_MESSAGE_ADDTWOINTS_H
